#cloud-config
package_upgrade: true
packages:
  - cockpit
  - cockpit-pcp
users:
  - default
  - name: ubuntu
    ssh-authorized-keys:
      - "{{ ssh_key }}"
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
ssh_pwauth: True
chpasswd:
  list: |
    ubuntu:password